blog/urls.py
from django.urls import path
from blog.views import blog_home,create_blog_post_view, post_edit_view, all_posts_view,post_detail_view, fav_update_view, tag_view, category_view
app_name = 'blog'

urlpatterns = [
    path('blog-home/', blog_home , name='blog_home'),
    path('create-blog/', create_blog_post_view , name='create_blog'),
    path('post/<slug:post_slug>/edit/', post_edit_view, name='post_edit_view'),
    # Category and Tag view
    path('category/<slug:category_slug>/', category_view, name='category_view'),
    path('tag/<slug:tag_slug>/', tag_view, name='tag_view'),

    # Read
    path('read/<slug:user_slug>/', all_posts_view, name='all_posts_view'),
    path('read/<slug:user_slug>/<slug:post_slug>/', post_detail_view, name='post_detail_view'),
    
    # Fav update using axios
    path('fav-update/', fav_update_view, name='fav_update_view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path('home/', home_view, name='home_view'),
    path('admin/', admin.site.urls,name='admin'),
    
    # ACCOUNT
    path('', include('account.urls', namespace='account')),

    # STUDENT
    path('', include('student.urls',namespace='student')),

    # TEACHER
    path('', include('teacher.urls', namespace='teacher')),

    # BLOG
    path('', include('blog.urls', namespace='blog')),

    # ASSIGNMENT
    path('', include('assignment.urls', namespace='assignment')),

    # ATTENDANCE
    path('', include('attendance.urls', namespace='attendance')),

    # APPOINTMENT
    path('', include("appointment.urls", namespace="appointment")),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

teacher/urls.py
from django.urls import path

from teacher.views import (
    teacher_dashboard,
    teacher_profile_overview,
    teacher_profile_edit,
    teacher_create_timetable,
    activate_student,
    teacher_create_classroom,
    add_student_classroom,
    remove_student_from_classroom,
    student_list
)


app_name = 'teacher'

urlpatterns = [
    path('teacher-dashboard/', teacher_dashboard, name='teacher_dashboard'),
    path('teacher-profile/<slug:user_slug>/',
         teacher_profile_overview, name='teacher_profile_overview'),
    path('teacher-profile/<slug:user_slug>/edit/',
         teacher_profile_edit, name='teacher_profile_edit'),
    path('teacher-create-timetable/', teacher_create_timetable,
         name='teacher_create_timetable'),
    path('teacher_dashboard/activate_student/<int:student_id>/',
         activate_student, name='activate_student'),
    path('teacher-create-classroom/', teacher_create_classroom,
         name='teacher_create_classroom'),
    path('teacher-create-student-classroom/',
         add_student_classroom, name='add_student_classroom'),
    path('edit-student-classroom/<slug:classroom_slug>/',
         remove_student_from_classroom, name='remove_student_from_classroom'),
    path('student-list/',
         student_list, name='student_list'),

]

teacher/models.py
from django.urls import reverse
from autoslug import AutoSlugField
from django.db import models

# Models
from account.models import User


# Create your models here.

class TeacherProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = AutoSlugField(unique=True)
    birth_date = models.DateField(null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    experience = models.IntegerField(null=True, blank=True)
    salary = models.IntegerField(null=True, blank=True)
    classroom = models.OneToOneField('student.StudentClassroom', null=True, blank=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name} (ID: {self.pk})"
    def save(self, *args, **kwargs):
        # Populate the slug field from user's username
        if not self.slug:
            self.slug = self.user.username
        super().save(*args, **kwargs)

    def get_absolute_url_overview(self):
        return reverse(
            'teacher:teacher_profile_overview',
            kwargs={'user_slug': self.slug}
        )
    
    def get_absolute_url_edit_teacher(self):
        return reverse('teacher:teacher_profile_edit', kwargs={'user_slug': self.slug})
    

teacher/forms.py
from django import forms

# Models
from teacher.models import TeacherProfile
from classroom.models import Timetable, Classroom
from student.models import StudentClassroom
class DateInput(forms.DateInput):
    input_type = 'date'
    format = '%d.%m.%Y'  # Format used in the form input


class TeacherProfileModelForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    profile_image = forms.ImageField(required=False)
    birth_date = forms.DateField(widget=DateInput(format='%d.%m.%Y'), required=False)
    
    class Meta:
        model = TeacherProfile
        fields = [
            'profile_image',
            'first_name',
            'birth_date',
            'bio',
            'phone_number',
            'address',
            'experience',
            'salary',
        ]
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Pre-fill the birth date field if the instance has a birth date
        if self.instance and self.instance.birth_date:
            self.fields['birth_date'].initial = self.instance.birth_date


# TODO:birth_date tarafında ne zaman edit yapmak istesek birth_day girilmesi gerekiyor, düzeltilmesi lazım

class TeacherTimetableModelForm(forms.ModelForm):
    class Meta:
        model = Timetable
        fields = [
            'classroom',
            'day_of_week',
            'start_time',
            'end_time',
            'subject',
        ]
        widgets = {
            'classroom': forms.Select(attrs={'class': 'form-control w-100'}),
            'day_of_week': forms.Select(attrs={'class': 'form-control w-100'}),
            'start_time': forms.TimeInput(attrs={'class': 'form-control w-100'}),
            'end_time': forms.TimeInput(attrs={'class': 'form-control w-100'}),
            'subject': forms.TextInput(attrs={'class': 'form-control w-100'}),
        }

class TeacherCreateClassroom(forms.ModelForm):
    class Meta:
        model = Classroom
        fields = [
            'name',
            'grade_level',
            'capacity',
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control w-100'}),
            'grade_level': forms.TextInput(attrs={'class': 'form-control w-100'}),
            'capacity': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        }

class CreateStudentClassroom(forms.ModelForm):
    class Meta:
        model = StudentClassroom
        fields = [
            'classroom',
            'students',
        ]
        widgets = {
            'classroom': forms.Select(attrs={'class': 'form-control w-100'}),
            'students': forms.SelectMultiple(attrs={'class': 'form-control w-100'}),
        }

class EditStudentClassroom(forms.ModelForm):
    students = forms.ModelMultipleChoiceField(
        queryset=None, # type: ignore
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = StudentClassroom
        fields = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['students'].queryset = self.instance.students.all()
        

teacher/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.db.models import Q
from django.contrib import messages

# FORMS
from teacher.forms import TeacherProfileModelForm, TeacherTimetableModelForm, TeacherCreateClassroom, CreateStudentClassroom, EditStudentClassroom

# MODELS
from classroom.models import Classroom, Timetable
from student.models import StudentClassroom, StudentProfile
from teacher.models import TeacherProfile


def teacher_dashboard(request):
    # Assuming you have a way to identify the currently logged-in teacher, e.g., request.user
    # Retrieve the teacher's profile
    teacher_profile = TeacherProfile.objects.get(user=request.user)
    # Retrieve the responsible class for the teacher
    responsible_class = StudentClassroom.objects.filter(
        responsible_teacher=teacher_profile)

    students = []
    for classroom in responsible_class:
        students = classroom.students.all()
    if responsible_class:
        students_in_class = students
    else:
        students_in_class = []

    # You can pass the students_in_class queryset to your template for rendering
    context = dict(
        students_in_class=students_in_class,
    )

    return render(request, 'teacher/teacher_dashboard.html', context)


def teacher_profile_overview(request, user_slug):
    teacher_profile = get_object_or_404(TeacherProfile, slug=user_slug)
    context = dict(
        teacher_profile=teacher_profile,
    )
    return render(request, 'teacher/teacher_profile/teacher_profile_overview.html', context)


def teacher_profile_edit(request, user_slug):
    user = request.user
    profile = get_object_or_404(TeacherProfile, slug=user_slug)
    initial_data = dict(
        first_name=user.first_name,
        last_name=user.last_name,
    )
    form = TeacherProfileModelForm(instance=profile, initial=initial_data)
    if request.method == "POST":
        form = TeacherProfileModelForm(
            request.POST or None,
            request.FILES or None,
            instance=profile
        )
        if form.is_valid():
            f = form.save(commit=False)
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            new_profile_image = form.cleaned_data.get('profile_image')
            if new_profile_image:
                user.profile_image = new_profile_image
                user.save()

            user.save()
            profile.save()
            f.save()
            return redirect('teacher:teacher_profile_overview', user_slug=user_slug)

    context = dict(
        form=form,
        title="Edit Profile",
        profile=profile,

    )
    return render(request, 'student/student_profile/student_profile_settings.html', context)

# TODO: for create-timetable add editing if teacher add wrong timetable


def teacher_create_timetable(request):
    form = TeacherTimetableModelForm()
    if request.method == "POST":
        form = TeacherTimetableModelForm(request.POST)
        if form.is_valid():

            # find the logged user in TeacherProfile model
            teacher_profile = get_object_or_404(
                TeacherProfile, user=request.user)
            form.instance.teacher = teacher_profile
            form.save()
            return redirect('teacher:teacher_dashboard')
    context = dict(
        form=form,
        title="Create Timetable",
    )
    return render(request, 'teacher/teacher_create_timetable.html', context)


def teacher_create_classroom(request):
    teacher = get_object_or_404(TeacherProfile, user=request.user)
    student_classroom = StudentClassroom.objects.filter(
        responsible_teacher=teacher)
    form = TeacherCreateClassroom()
    if request.method == "POST":
        form = TeacherCreateClassroom(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            grade_level = form.cleaned_data['grade_level']
            if Classroom.objects.filter(name=name, grade_level=grade_level).exists():
                context = dict(
                    form=form,
                    title='Create Classroom'
                )
                messages.info(
                    request, f"{grade_level}-{name}  already exists.")
                return render(request, 'teacher/teacher_classroom_create.html', context)
            else:
                form.instance.responsible_teacher = teacher
                classroom = form.save()
                student_classroom = StudentClassroom.objects.create(
                    classroom=classroom, responsible_teacher=teacher)
                student_classroom.save()
                form.save()
                return redirect('teacher:teacher_dashboard')
    context = dict(
        form=form,
        title="Create Classroom",
    )
    return render(request, 'teacher/teacher_classroom_create.html', context)


def add_student_classroom(request):
    form = CreateStudentClassroom()
    initial_data = dict(

    )
    if request.method == "POST":
        form = CreateStudentClassroom(request.POST)
        if form.is_valid():
            classroom = form.cleaned_data['classroom']
            students = form.cleaned_data['students']

            # Check if a StudentClassroom already exists for this classroom
            student_classroom, created = StudentClassroom.objects.get_or_create(
                classroom=classroom)

            # Check if the selected students are already associated with the classroom
            existing_students = student_classroom.students.all()
            new_students = set(students) - set(existing_students)

            if not new_students:
                print('These students are already in the classroom.')
                return redirect('teacher:teacher_dashboard')

            # Add new students to the existing classroom
            student_classroom.students.add(*new_students)

            # Save the StudentClassroom object
            student_classroom.save()

            teacher_profile = get_object_or_404(
                TeacherProfile, user=request.user)
            student_classroom.responsible_teacher = teacher_profile
            student_classroom.save()

            for student in new_students:
                student.classroom = student_classroom
                student.save()

            return redirect('teacher:teacher_dashboard')

    context = dict(
        form=form,
        title="Add Students to Classroom",
    )
    return render(request, 'teacher/teacher_classroom_create.html', context)

# TODO: öğrenciler için pagenation ekle ve #Usermanagement->Users içindeki list gibi yap actions kısmını o şekilde ayarlayabilirsin
# TODO: Teacherlar hangi sınıfa responsible olduğunu kaydedip editlemesi gerekir ve bu izinle olmalı!!


def remove_student_from_classroom(request, classroom_slug):

    classroom = get_object_or_404(StudentClassroom, slug=classroom_slug)
    teacher_profile = get_object_or_404(TeacherProfile, user=request.user)

    # Ensure that only teachers can remove students from the classroom (you can modify this logic)
    if not request.user.role == 'teacher':
        return redirect('teacher_dashboard')
    if classroom.responsible_teacher != teacher_profile:
        messages.info(request, f'You are not responsible for this classroom, please contact your manager!')
        return redirect('teacher:teacher_dashboard')

    if request.method == "POST" and request.user.role == 'teacher':

        form = EditStudentClassroom(request.POST, instance=classroom)

        if form.is_valid():
            # Get the selected students to be removed
            selected_students = form.cleaned_data.get('students')

            # Remove the selected students from the classroom
            classroom.students.remove(*selected_students)

            for student in selected_students:
                student.classroom = None
                student.save()

            return redirect('teacher:teacher_dashboard')
    else:
        form = EditStudentClassroom(instance=classroom)

    context = {
        'form': form,
        'classroom': classroom,
        'title': "Edit Students in Classroom",
    }
    return render(request, 'teacher/edit_student_classroom.html', context)


def activate_student(request, student_id):
    # Ensure that only teachers can activate students (you can modify this logic)
    if not request.user.role == 'teacher':
        return redirect('teacher_dashboard')

    student = get_object_or_404(StudentProfile, id=student_id)

    # Activate the student
    student.phone_number_active = True
    student.save()

    # Optionally, change the status from "not verified" to "verified"
    # You need to define the appropriate field in your StudentProfile model for this status.

    return redirect('teacher:teacher_dashboard')


def student_list(request):
    # Ensure that only teachers can view the list of users (you can modify this logic)
    if not request.user.role == 'teacher':
        return redirect('teacher_dashboard')
    user = request.user 
    teacher = get_object_or_404(TeacherProfile, user=user)
    classroom = get_object_or_404(StudentClassroom, responsible_teacher= teacher)
    # Retrieve the list of students
    students = classroom.students.all()
    # Retrieve the list of teachers
    teachers = TeacherProfile.objects.all()

    context = {
        'students': students,
        'teachers': teachers,
    }
    return render(request, 'teacher/student_list.html', context)

teacher/templates/teacher/create_student_classroom.html
{% extends 'core/base.html' %} 
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!--begin::Basic info-->
<div class="card mb-5 mb-xl-10">
	<!--begin::Card header-->
	<div class="card-header border-0 cursor-pointer" role="button" data-bs-toggle="collapse" data-bs-target="#kt_account_profile_details" aria-expanded="true" aria-controls="kt_account_profile_details">
		<!--begin::Card title-->
		<div class="card-title m-0">
			<h3 class="fw-bold m-0">{{ title }}</h3>
		</div>
		<!--end::Card title-->
	</div>
	<!--begin::Card header-->
	<!--begin::Content-->
	<div id="kt_account_settings_profile_details" class="collapse show d-flex flex-center">
		<!--begin::Form-->
		<form id="kt_account_profile_details_form" class="form w-50" enctype="multipart/form-data" method="post">
			{% csrf_token %}
			<!--begin::Card body-->
			<div class="card-body border-top p-9">
				{{ form|crispy }}
			</div>
			<!--end::Card body-->
			<!--begin::Actions-->
			<div class="card-footer d-flex justify-content-end py-6 px-9">
				<button type="reset" class="btn btn-light btn-active-light-primary me-2">Discard</button>
				<button type="submit" class="btn btn-primary" id="kt_account_profile_details_submit">Save Changes</button>
			</div>
			<!--end::Actions-->
		</form>
		<!--end::Form-->
	</div>
	<!--end::Content-->
</div>
<!--end::Basic info-->
{% endblock content %}

teacher/templates/teacher/edit_student_classroom.html
{% extends 'core/base.html' %} 
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!--begin::Basic info-->
<div class="card mb-5 mb-xl-10">
	<!--begin::Card header-->
	<div class="card-header border-0 cursor-pointer" role="button" data-bs-toggle="collapse" data-bs-target="#kt_account_profile_details" aria-expanded="true" aria-controls="kt_account_profile_details">
		<!--begin::Card title-->
		<div class="card-title m-0">
			<h3 class="fw-bold m-0">{{ title }}</h3>
		</div>
		<!--end::Card title-->
	</div>
	<!--begin::Card header-->
	<!--begin::Content-->
	<div class="collapse show d-flex flex-center">
		<!--begin::Form-->
		<form method="post" class="mb-5">
			{% csrf_token %}
			<h2>Students in Classroom:</h2>
			{{ form.as_p }}
			<div class="d-flex flex-end">
				<button type="submit" class="">Save Changes</button>
			</div>	
		</form>
		
		
		<!--end::Form-->
	</div>
	<!--end::Content-->
</div>
<!--end::Basic info-->
{% endblock content %}

teacher/templates/teacher/student_card.html
<section>
  <div class="swiper mySwiper container">
    <div class="swiper-wrapper content">
      {% for student in students_in_class %}

      <div class="swiper-slide card">
        <div class="card-content">
          <div class="image">
            <img src="{{ student.user.profile_image.url }}" alt="" />
          </div>

          <div class="media-icons">
            <i class="fab fa-facebook"></i>
            <i class="fab fa-twitter"></i>
            <i class="fab fa-github"></i>
          </div>

          <div class="name-profession">
            <span class="name">{{ student.user.first_name }}</span>
            <span class="profession">{{ student.user.role }}</span>
          </div>

          <div class="rating">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
          </div>

          <div class="button">
            <button class="aboutMe">About Me</button>
            {% if student.phone_number %}
              <form method="post" action="{% url 'teacher:activate_student' student.id %}">
                  {% csrf_token %}
                  <input type="submit" value="Activate Student">
              </form>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  <div class="swiper-button-next"></div>
  <div class="swiper-button-prev"></div>
  <div class="swiper-pagination"></div>
</section>

teacher/templates/teacher/teacher_classroom_create.html
{% extends 'core/base.html' %} 
{% load static %} 
{% load crispy_forms_tags %} 
{% block content %}
<!--begin::Basic info-->
<div class="card mb-5 mb-xl-10">
  <!--begin::Card header-->
  <div
    class="card-header border-0 cursor-pointer"
    role="button"
    data-bs-toggle="collapse"
    data-bs-target="#kt_account_profile_details"
    aria-expanded="true"
    aria-controls="kt_account_profile_details"
  >
    <!--begin::Card title-->
    <div class="card-title m-0">
      <h3 class="fw-bold m-0">{{ title }}</h3>
    </div>
    <a
      href="{% url 'teacher:teacher_dashboard' %}"
      class="btn btn-sm btn-primary align-self-center"
      >
        <div class="d-flex align-items-center justify-content-center">
          <div>
            Edit Student Classroom
          </div>
        </div>
    </a>
    <!--end::Card title-->
  </div>
  <!--begin::Card header-->
  <!--begin::Content-->
  
  <div
    id="kt_account_settings_profile_details"
    class="collapse show d-flex flex-center"
  >
    <!--begin::Form-->
    <form
      id="kt_account_profile_details_form"
      class="form w-50"
      enctype="multipart/form-data"
      method="post"
    >
      {% csrf_token %}
      <!--begin::Card body-->
      <div class="card-body border-top p-9">{{ form|crispy }}</div>
      <!--end::Card body-->
      <!--begin::Actions-->
      <div class="card-footer d-flex justify-content-end py-6 px-9">
        <button
          type="reset"
          class="btn btn-light btn-active-light-primary me-2"
        >
          Discard
        </button>
        <button
          type="submit"
          class="btn btn-primary"
          id="kt_account_profile_details_submit"
        >
          Save Changes
        </button>
      </div>
      <!--end::Actions-->
    </form>
    <!--end::Form-->
  </div>
  <!--end::Content-->
</div>
<!--end::Basic info-->
{% endblock content %}

teacher/templates/teacher/teacher_create_timetable.html
{% extends 'core/base.html' %} 
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!--begin::Basic info-->
<div class="card mb-5 mb-xl-10">
	<!--begin::Card header-->
	<div class="card-header border-0 cursor-pointer" role="button" data-bs-toggle="collapse" data-bs-target="#kt_account_profile_details" aria-expanded="true" aria-controls="kt_account_profile_details">
		<!--begin::Card title-->
		<div class="card-title m-0">
			<h3 class="fw-bold m-0">{{ title }}</h3>
		</div>
		<!--end::Card title-->
	</div>
	<!--begin::Card header-->
	<!--begin::Content-->
	<div id="kt_account_settings_profile_details" class="collapse show d-flex flex-center">
		<!--begin::Form-->
		<form id="kt_account_profile_details_form" class="form w-50" enctype="multipart/form-data" method="post">
			{% csrf_token %}
			<!--begin::Card body-->
			<div class="card-body border-top p-9">
				{{ form|crispy }}
			</div>
			<!--end::Card body-->
			<!--begin::Actions-->
			<div class="card-footer d-flex justify-content-end py-6 px-9">
				<button type="reset" class="btn btn-light btn-active-light-primary me-2">Discard</button>
				<button type="submit" class="btn btn-primary" id="kt_account_profile_details_submit">Save Changes</button>
			</div>
			<!--end::Actions-->
		</form>
		<!--end::Form-->
	</div>
	<!--end::Content-->
</div>
<!--end::Basic info-->
{% endblock content %}

teacher/templates/teacher/teacher_dashboard.html
{% extends 'core/base.html' %} {% load static %} {% block css %}
<link
  href="{% static 'assets/css/student_card.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<link rel="stylesheet" href="{% static 'assets/css/swiper-bundle.min.css' %}" />
<!-- ===== Fontawesome CDN Link ===== -->
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
/>
{% endblock css %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      {% include 'teacher/student_card.html' %}
      <h1>Students in Classrooms:</h1>
      <ul>
       {% if students_in_class %}
          <h2>Students in Your Class</h2>
          <ul>
              {% for student in students_in_class %}
              <li>{{ student.user.first_name }} {{ student.user.last_name }}</li>
              <!-- You can display other student information here -->
              {% endfor %}
          </ul>
        {% else %}
        <p>You are not responsible for any class at the moment.</p>
        {% endif %}
      </ul>
      <hr />
      <div class="d-flex flex-direction-column">
        <div>
          <a
            class="bg-primary text-light mx-1"
            href="{% url 'teacher:teacher_profile_overview' user_slug=profile_global.slug %}"
            >Profile</a
          >
          <a
            class="bg-danger text-dark mx-1"
            href="{% url 'teacher:teacher_create_timetable'%}"
            >Create TimeTable</a
          >
          <a
            class="bg-dark text-light mx-1"
            href="{% url 'teacher:teacher_create_classroom' %}"
            >Create Classroom</a
          >
          <a
            class="bg-white text-dark mx-1"
            href="{% url 'teacher:add_student_classroom' %}"
            >Add Student to Classroom</a
          >
          <a
            class="bg-white text-danger mx-1" 
            href="{% url 'teacher:remove_student_from_classroom' classroom_slug=profile_global.classroom.slug %}"
            >Remove Student from classroom</a
          >
          <a
            class="bg-danger text-white mx-1" 
          href="{% url 'teacher:student_list' %}"
            >Student List</a
          >
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %} {% block js %}
<!-- Swiper JS -->
<script src="{% static 'assets/js/swiper-bundle.min.js' %}"></script>

<!-- Initialize Swiper -->
<script>
  var swiper = new Swiper(".mySwiper", {
    slidesPerView: 3,
    spaceBetween: 30,
    slidesPerGroup: 3,
    loop: true,
    loopFillGroupWithBlank: true,
    pagination: {
      el: ".swiper-pagination",
      clickable: true,
    },
    navigation: {
      nextEl: ".swiper-button-next",
      prevEl: ".swiper-button-prev",
    },
  });
</script>
{% endblock js %}