assignment/urls.py
from django.urls import path
from .views import create_quiz, quiz_detail, solve_quiz, quiz_results, create_questions, solve_quiz_lists, create_assignment, assignment_list,assignment_detail, uploded_solution_list
app_name = 'assignment'
urlpatterns = [
    path('create-quiz/', create_quiz, name='create_quiz'),
    path('quiz/<int:quiz_id>/', quiz_detail, name='quiz_detail'),
    path('solve_quiz/<int:quiz_id>/', solve_quiz, name='solve_quiz'),
    path('quiz_results/<int:quiz_id>/<slug:student_slug>',
         quiz_results, name='quiz_results'),
    path('create_questions/', create_questions, name='create_questions'),
    path('quiz-lists/', solve_quiz_lists, name='solve_quiz_lists'),

    # ASSIGNMENT VIA UPLOADING FILE
    # for teacher
    path('create-assignment/', create_assignment, name='create_assignment'),
    path('uploaded-solutions/<slug:classroom_slug>', uploded_solution_list, name='uploded_solution_list'),
    # for student
    path('assignment-list/<slug:classroom_slug>/<slug:student_slug>', assignment_list, name='assignment_list'), 
    path('assignment-detail/<int:assignment_id>/', assignment_detail, name='assignment_detail'),
]

blog/urls.py
from django.urls import path
from blog.views import blog_home,create_blog_post_view, post_edit_view, all_posts_view,post_detail_view, fav_update_view, tag_view, category_view
app_name = 'blog'

urlpatterns = [
    path('blog-home/', blog_home , name='blog_home'),
    path('create-blog/', create_blog_post_view , name='create_blog'),
    path('post/<slug:post_slug>/edit/', post_edit_view, name='post_edit_view'),
    # Category and Tag view
    path('category/<slug:category_slug>/', category_view, name='category_view'),
    path('tag/<slug:tag_slug>/', tag_view, name='tag_view'),

    # Read
    path('read/<slug:user_slug>/', all_posts_view, name='all_posts_view'),
    path('read/<slug:user_slug>/<slug:post_slug>/', post_detail_view, name='post_detail_view'),
    
    # Fav update using axios
    path('fav-update/', fav_update_view, name='fav_update_view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path('home/', home_view, name='home_view'),
    path('admin/', admin.site.urls,name='admin'),
    
    # ACCOUNT
    path('', include('account.urls', namespace='account')),

    # STUDENT
    path('', include('student.urls',namespace='student')),

    # TEACHER
    path('', include('teacher.urls', namespace='teacher')),

    # BLOG
    path('', include('blog.urls', namespace='blog')),

    # ASSIGNMENT
    path('', include('assignment.urls', namespace='assignment')),

    # ATTENDANCE
    path('', include('attendance.urls', namespace='attendance')),

    # APPOINTMENT
    path('', include("appointment.urls", namespace="appointment")),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

assignment/models.py
# quiz/models.py
from django.db import models
from django.urls import reverse
from config.validators import validate_file_extension
from student.models import StudentProfile
from teacher.models import TeacherProfile

# ASSIGNMENT VIA QUIZ
class Quiz(models.Model):
    title = models.CharField(max_length=255)
    teacher = models.ForeignKey(TeacherProfile, on_delete=models.CASCADE)
    # deadline with a default value 
    deadline = models.DateTimeField(blank=True, null=True)    
    def __str__(self):
        return self.title

    def get_solve_quiz_url(self):
        return reverse(
            "assignment:solve_quiz",
            kwargs={
                "quiz_id": self.pk,
            },
        )
    
    class Meta:
        ordering = ('deadline',)

class Question(models.Model):
    text = models.CharField(max_length=255)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    # added a new field to the Question model which is realted o score of the question
    score = models.IntegerField(default=1)
    def __str__(self) -> str:
        return self.text


class Choice(models.Model):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name='choice_set')
    text = models.CharField(max_length=100)
    is_correct = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.text


class Result(models.Model):
    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    score = models.IntegerField()

    def __str__(self) -> str:
        return str(self.score)


class UserAnswer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='user_answers')
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE, related_name='user_answers')
    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE,null=True, blank=True)

    class Meta:
        unique_together = ('question', 'student')

    def __str__(self) -> str:
        return self.choice.text

class SolvedQuiz(models.Model):
    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    score = models.IntegerField()
    date_solved = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.student} solved {self.quiz} with score {self.score}"

# ASSIGNMENT VIA UPLOADING FILE
class AssignmentFile(models.Model):
    title = models.CharField(max_length=100)
    teacher = models.ForeignKey(TeacherProfile, on_delete=models.CASCADE)
    description = models.TextField()
    deadline = models.DateTimeField()
    classroom = models.ForeignKey('student.StudentClassroom', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('deadline',)

class UploadedSolution(models.Model):
    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE)
    assignment = models.ForeignKey(AssignmentFile, on_delete=models.CASCADE)
    file = models.FileField(upload_to='uploads/', validators=[validate_file_extension])
    uploaded_at = models.DateTimeField(auto_now_add=True)

assignment/forms.py
# forms.py
from .models import AssignmentFile, Choice, UploadedSolution
from django import forms
from .models import Quiz, Question, Choice

# ASSIGNMENT VIA QUIZ


class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ['title']


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = [
            'text',
            'quiz'
        ]


ChoiceFormSet = forms.inlineformset_factory(
    Question, Choice, fields=('text', 'is_correct'), extra=1, can_delete=False)

# ASSIGNMENT VIA UPLOADING FILE


class AssignmentForm(forms.ModelForm):
    class Meta:
        model = AssignmentFile
        fields = ['title', 'deadline', 'description', 'classroom']
        widgets = {
            'deadline': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }


class UploadedSolutionForm(forms.ModelForm):
    class Meta:
        model = UploadedSolution
        fields = ['file']

assignment/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from .forms import AssignmentForm, ChoiceFormSet, QuizForm, QuestionForm, UploadedSolutionForm
from django.contrib.auth.decorators import login_required

from assignment.models import AssignmentFile, Quiz, Choice, Result, SolvedQuiz, UploadedSolution, UserAnswer
from teacher.models import TeacherProfile
from student.models import StudentClassroom, StudentProfile
from django.http import HttpResponse

from django.core.exceptions import ValidationError
from assignment.validation import validate_quiz_id, validate_student_slug


@login_required(login_url='account:error_view')
def create_quiz(request):
    if request.user.role == 'teacher':
        if request.method == 'POST':
            form = QuizForm(request.POST)
            if form.is_valid():
                teacher_profile = get_object_or_404(
                    TeacherProfile, user=request.user)
                quiz = form.save(commit=False)
                quiz.teacher = teacher_profile
                quiz.save()
                return redirect('teacher:teacher_dashboard')
        else:
            form = QuizForm()
        return render(request, 'assignment/create_quiz.html', {'form': form})
    else:
        messages.warning(request, "You are not authorized to create a quiz!")
        return redirect('student:student_dashboard')


@login_required(login_url='account:error_view')
def create_questions(request):
    if request.method == 'POST':
        print(request.POST)
        question_form = QuestionForm(request.POST)
        choice_formset = ChoiceFormSet(request.POST)
        print("before if")
        if question_form.is_valid() and choice_formset.is_valid():
            # Save the quiz
            print("inside if")
            # Save the question associated with the quiz

            question = question_form.save(commit=False)
            question.quiz.pk = question_form.cleaned_data['quiz']
            question.save()
            choice = choice_formset.save(commit=False)
            upper_bound = int(request.POST.get('choice_set-TOTAL_FORMS'))
            print(choice)
            # TODO: kullanıcı boş gönderdiği zaman hata alıyoruz!!
            for i in range(0, upper_bound):
                choice[i].question = question
                choice[i].text = request.POST.get(f'choice_set-{i}-text')
                choice[i].save()
            # Redirect to a view that lists all quizzes
            return redirect('assignment:create_quiz')

    else:
        question_form = QuestionForm()
        choice_formset = ChoiceFormSet()

    context = {
        'title': 'Create Questions',
        'question_form': question_form,
        'choice_formset': choice_formset,
    }

    return render(request, 'assignment/create_questions.html', context)


def quiz_detail(request, quiz_id):
    quiz = Quiz.objects.get(id=quiz_id)
    questions = quiz.question_set.all()  # type: ignore
    return render(request, 'quiz_detail.html', {'quiz': quiz, 'questions': questions})


@login_required(login_url='account:error_view')
def solve_quiz(request, quiz_id):
    user = request.user
    student_profile = get_object_or_404(StudentProfile, user=user)
    quiz = get_object_or_404(Quiz, id=quiz_id)
    questions = quiz.question_set.all()  # type: ignore
    questions_choices = [(question, question.choice_set.all())
                         for question in questions]
    # print(questions_choices)
    # Check if the user has already solved the quiz
    result_exists = Result.objects.filter(
        student=student_profile, quiz=quiz).exists()
    if result_exists:
        messages.info(request, f'You have already solved {quiz.title}')
        return redirect('assignment:quiz_results', quiz_id=quiz.pk, student_slug=student_profile.slug)

    if request.method == 'POST':
        print(request.POST)
        score = 0
        for i, question in enumerate(questions, 1):
            selected_choice = request.POST.get(f'question{i}')
            print(selected_choice)
            if selected_choice:
                print("--------------------before choice")
                choice = question.choice_set.get(id=int(selected_choice))
                # save the user answer on model UserAnswer
                # Assuming the user's answer is sent in the request.POST data
                user_choice = Choice.objects.get(id=selected_choice)
                # Create and save the UserAnswer

                user_answer = UserAnswer(
                    question=question, choice=user_choice, student=student_profile)
                user_answer.save()
                if choice.is_correct:
                    score += question.score
                print("after choice--------------------")
                # if choice.is_correct:
                #     score += 1

        if request.user.role == 'student':
            # Save the quiz into the SolvedQuiz model
            solved_quiz = SolvedQuiz(
                quiz=quiz, student=student_profile, score=score)
            solved_quiz.save()
            result, created = Result.objects.get_or_create(
                student=student_profile, quiz=quiz, score=score)
            if created:
                result.save()
            return redirect('assignment:quiz_results', quiz_id=quiz.pk, student_slug=student_profile.slug)

    include_input = True
    context = dict(
        quiz=quiz,
        questions=questions,
        questions_choices=questions_choices,
        include_input=include_input
    )

    return render(request, 'assignment/solve_quiz.html', context)


def quiz_results(request, quiz_id, student_slug):
    """View function to show the results of a quiz.""" # TODO: There are some errors, check it out!
    try:
        validate_quiz_id(quiz_id)
        validate_student_slug(student_slug)
    except ValidationError as e:
        return redirect("account:error_view")

    student = get_object_or_404(StudentProfile, slug=student_slug)
    quiz = Quiz.objects.get(id=quiz_id)
    result = get_object_or_404(Result, quiz=quiz, student=student)
    print("Result", result)
    user_answers = UserAnswer.objects.filter(student=student)
    questions_choices = [(answer.question, answer.choice)
                         for answer in user_answers]

    print(questions_choices)

    include_input = False
    context = dict(
        quiz=quiz,
        result=result,
        questions_choices=questions_choices,
        include_input=include_input
    )
    return render(request, 'assignment/quiz_results.html', context)


def solve_quiz_lists(request):
    """View function to show the results of a quiz."""
    student = get_object_or_404(StudentProfile, user=request.user)
    quizzes = Quiz.objects.all()
    solved_quizes = SolvedQuiz.objects.filter(student=student)

    context = dict(
        quizzes=quizzes,
        solved_quizes=solved_quizes
    )
    return render(request, 'assignment/solve_quiz_lists.html', context)


# ASSIGNMENT VIA UPLOADING FILE
def create_assignment(request):
    user = request.user
    teacher_profile = get_object_or_404(TeacherProfile, user=user)
    if request.method == 'POST':
        form = AssignmentForm(request.POST)
        if form.is_valid():
            assignment = form.save(commit=False)
            assignment.teacher = teacher_profile
            assignment.save()
    else:
        form = AssignmentForm()
    return render(request, 'assignment/create_assignment.html', {'form': form})

def uploded_solution_list(request, classroom_slug):
    user = request.user
    teacher = get_object_or_404(TeacherProfile, user=user)
    solutions = UploadedSolution.objects.filter(assignment__teacher=teacher, 
                                                assignment__classroom__slug=classroom_slug)
    context = dict(
        solutions=solutions
    )
    return render(request, "assignment/upladed_solutions.html", context)
#TODO: Hangi sınıfa ne verdiğini göremiyor, hoca 8-A seçerse ona ait assignmentlerı görmesi gerekir! Başkasını seçerse başkasını!!

def assignment_list(request, classroom_slug, student_slug):
    student = get_object_or_404(StudentProfile, slug=student_slug)
    classroom = get_object_or_404(StudentClassroom, slug=classroom_slug)
    assignments = AssignmentFile.objects.filter(classroom=classroom)
    if student.classroom != classroom:
        messages.info(request, f'You are not in this classroom!')
        return redirect('student:student_dashboard')
    
    print(assignments)
    context = dict(
        assignments=assignments,
        student=student
    )
    return render(request, 'assignment/assignment_list.html', context)

@login_required(login_url='account:error_view')
def assignment_detail(request, assignment_id):
    student = get_object_or_404(StudentProfile, user=request.user)
    assignment = AssignmentFile.objects.get(pk=assignment_id)
    if request.user.role == 'teacher':
        return redirect('teacher:teacher_dashboard')
    if request.method == 'POST':
        form = UploadedSolutionForm(request.POST, request.FILES)
        if form.is_valid():
            solution = form.save(commit=False)
            solution.student = student
            solution.assignment = assignment
            solution.save()
    else:
        form = UploadedSolutionForm()

    context = dict(
        assignment=assignment,
        form=form
    )
    return render(request, 'assignment/assignment_detail.html', context)

# DONE: add assignment list for student, tıkladıkan sonra assignment detayı ve upload yapabilecek, description ı görsün diye!
# DONE: hangi sınıfa olduğunu girmesi gerekir hocanın assignment oluşturuken ve eğer o öğrenci o sınıfta yoksa göremez o assignmentı!
# TODO: teacher assignment yükleyenleri sınıflara göre görebilecek ve indirip bakabilecek ve not verebilecek!

assignment/templates/assignment/assignment_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">{{ assignment.title }}</h1>
                <p class="card-text"><span class="fw-bold">Teacher:</span> {{ assignment.teacher }}</p>
                <p class="card-text"><span class="fw-bold">Description:</span> {{ assignment.description }}</p>
                <p class="card-text"><span class="fw-bold">Deadline:</span> {{ assignment.deadline }}</p>
                <p class="card-text"><span class="fw-bold">Classroom:</span> {{ assignment.classroom }}</p>
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Upload Solution</button>
            </form>
        </div>
    </div>
{% endblock %}

assignment/templates/assignment/assignment_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
    <h1>Assignments</h1>
    <ul>
        {% for assignment in assignments %}
            <li>
                <a href="{% url 'assignment:assignment_detail' assignment.pk %}" class="btn btn-primary">{{ assignment.title }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

assignment/templates/assignment/create_assignment.html
{% extends 'core/base.html' %}
{% block content %}
    <h2>Creating Assignment</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Assignment</button>
    </form>
{% endblock %}

assignment/templates/assignment/create_questions.html
{% extends 'core/base.html' %}
{% block content %}
<div class="container mt-4">
    <div class="row mt-4">
        <div class="col-sm-6 offset-sm-2">
            <h2>{{ title }}</h2>
            <form method="post" class="my-10" enctype="multipart/form-data">
                {% csrf_token %}
                {{ question_form.as_p }}
                <div class="border border-success">
                </div>
                {{ choice_formset.management_form }}
                <table id="choice-formset">
                    {% for form in choice_formset %}
                        {{ form.as_table }}
                    {% endfor %}
                </table>
                <button type="button" id="add-choice-btn">Add Choice</button>
                <input type="submit" value="Save Quiz" href="{% url 'assignment:create_questions' %}">
                
            </form>
        </div>
    </div>
</div>
{% endblock content %}
{% block js %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Function to add a new choice row
        function addChoice() {
            console.log("girdim");
            const choiceContainer = document.getElementById('choice-formset');
            const totalForms = document.getElementById('id_choice_set-TOTAL_FORMS');
            console.log(totalForms.value)
            // Get the current form count
            const formCount = parseInt(totalForms.value);
            console.log(formCount);
            // Create a new form with the correct naming
            const newChoiceRow = document.createElement('tr');
            newChoiceRow.innerHTML = `
                <td><input type="text" name="choice_set-${formCount}-text"></td>
                <td><input type="checkbox" name="choice_set-${formCount}-is_correct"></td>
            `;
            
            // Increment the form count and update the TOTAL_FORMS field
            totalForms.value = formCount + 1;
            console.log(newChoiceRow);
            choiceContainer.appendChild(newChoiceRow);
        }

        // Add event listener for the "Add Choice" button
        const addChoiceBtn = document.getElementById('add-choice-btn');
        addChoiceBtn.addEventListener('click', addChoice);
    });


</script>

{% endblock js %}

assignment/templates/assignment/create_quiz.html
{% extends 'core/base.html' %}
{% block content %}
<!-- create_assignment.html -->
<div class="d-flex flex-column  align-items-center">
    <h2>Create Quiz</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Quiz</button>
    </form>
</div>
{% endblock content %}

assignment/templates/assignment/quiz_results.html
{% extends 'core/base.html' %}
{% block content %}
<div class="container mt-5">
    <div class="card" >
    <div class="d-flex flex-row justify-content-between align-items-center card-header mt-5">
            <h3>Quiz Results for {{ quiz.title }} </h3>
            <div class="d-flex flex-row align-items-center">
                <h5 class="card-title">Score:</h5>
                <p class="card-text display-1">{{ result.score }}</p>
            </div>
        </div>
        

            <div class="d-flex flex-column align-items-center card-body">
                <h1 class="card-title">Questions:</h1>
                {% include 'assignment/components/questions.html' with include_input=include_input %}
                <h4 class="card-title mt-2">Teacher:</h4>
                <p class="card-text">{{ result.quiz.teacher.user.get_full_name }}</p>            
            </div>

        </div>
    </div>
</div>
{% endblock content %}

assignment/templates/assignment/solve_quiz.html
{% extends 'core/base.html' %}
{% block content %}
<div class="container mt-5">
    <div class="card">
        <div class="d-flex flex-row justify-content-between align-items-center card-header mt-5">
            <div class="d-flex flex-column flex-start">
                <h6 class="flex-start">
                    {{ quiz.title }}
                </h6>
                <h6>
                    {{ quiz.teacher.user.get_full_name }}
                </h6>
            </div>
        </div>
        <div class="d-flex flex-column justify-content-center align-items-center mw-100">
            <form id="quiz-form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'assignment/components/questions.html' with include_input=include_input %}
            </form>
        </div>
    </div>
</div>

{% endblock content %}

{% block js %}
<script>
document.addEventListener('DOMContentLoaded', function() {
    const form = document.getElementById('quiz-form');
    const questions = form.querySelectorAll('.question');
    let currentQuestionIndex = 0;

    function showQuestion(index) {
        questions.forEach((question, idx) => {
            if (idx === index) {
                question.style.display = 'block';
            } else {
                question.style.display = 'none';
            }
        });
        if (index === questions.length - 1) {
            document.getElementById('next-question').style.display = 'none';
            document.getElementById('submit-quiz').style.display = 'block';
        } else {
            document.getElementById('next-question').style.display = 'block';
            document.getElementById('submit-quiz').style.display = 'none';
        }
        if (index === 0) {
            document.getElementById('previous-question').style.display = 'none';
        } else {
            document.getElementById('previous-question').style.display = 'block';
        }
    }

    function handlePreviousQuestion() {
        if (currentQuestionIndex > 0) {
            currentQuestionIndex--;
            showQuestion(currentQuestionIndex);
        }
    }

    function handleNextQuestion() {
        if (currentQuestionIndex < questions.length - 1) {
            currentQuestionIndex++;
            showQuestion(currentQuestionIndex);
        }
    }

    document.getElementById('previous-question').addEventListener('click', handlePreviousQuestion);
    document.getElementById('next-question').addEventListener('click', handleNextQuestion);

    // Initially hide the previous button when the page loads
    showQuestion(currentQuestionIndex);
});
</script>




{% endblock js %}

assignment/templates/assignment/upladed_solutions.html
{% extends 'core/base.html' %}
{% load basename %}
{% block content  %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Uploaded Solutions</h1>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Student</th>
                            <th>Assignment</th>
                            <th>File</th>
                            <th>Uploaded At</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for solution in solutions %}
                            <tr>
                                <td>{{ solution.student }}</td>
                                <td>{{ solution.assignment }}</td>
                                <td><a href="{{ solution.file.url }}">{{ solution.file.url|filename }}</a></td>
                                <td>{{ solution.uploaded_at }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}